export const GET_CLIP_LIST_REQUEST = 'GET_CLIP_LIST_REQUEST'
export const GET_CLIP_LIST_SUCCESS = 'GET_CLIP_LIST_SUCCESS'
export const GET_CLIP_LIST_FAILURE = 'GET_CLIP_LIST_FAILURE'

export const GET_PRESENTATION_CLIP_REQUEST = 'GET_PRESENTATION_CLIP_REQUEST'
export const GET_PRESENTATION_CLIP_FAILURE = 'GET_PRESENTATION_CLIP_FAILURE'
export const GET_PRESENTATION_CLIP_SUCCESS = 'GET_PRESENTATION_CLIP_SUCCESS'

export const CHANGED_PRESENTATION_CLIP = 'CHANGED_PRESENTATION_CLIP'

export const ADD_CLIP_REQUEST = 'ADD_CLIP_REQUEST'
export const ADD_CLIP_FAILURE = 'ADD_CLIP_FAILURE'
export const ADD_CLIP_SUCCESS = 'ADD_CLIP_SUCCESS'

export const REMOVE_CLIP_REQUEST = 'REMOVE_CLIP_REQUEST'
export const REMOVE_CLIP_FAILURE = 'REMOVE_CLIP_FAILURE'
export const REMOVE_CLIP_SUCCESS = 'REMOVE_CLIP_SUCCESS'

export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const SIGN_OUT_USER = 'SIGN_OUT_USER'

// export const CONNECTION_ESTABLISHED = 'CONNECTION_ESTABLISHED';
// export const CONNECTION_LOST = 'CONNECTION_LOST';
export const SET_EDITED_CLIP = 'SET_EDITED_CLIP'
export const EDIT_CLIP_REQUEST = 'EDIT_CLIP_REQUEST'
export const EDIT_CLIP_FAILURE = 'EDIT_CLIP_FAILURE'
export const EDIT_CLIP_SUCCESS = 'EDIT_CLIP_SUCCESS'

export const RESET_ERROR_AND_SUCCESSONEDIT = 'RESET_ERROR_AND_SUCCESSONEDIT'
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
